name: Deploy Moodle

on:
  push:
    branches: [ 'blue_39', 'blue_39_upgrade', 'blue_39_uat', 'blue_39_prod' ]
  pull_request:
    branches: [ 'blue_39', 'blue_39_upgrade', 'blue_39_uat', 'blue_39_prod' ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate deployment package
      uses: actions/checkout@v3
      with:
        submodules: true
    - run: zip -r ${{ github.sha}}-deploy.zip . -x '*.git*'
    - name: Deploy to Staging
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "Moodle Staging"
        environment_name: Moodlestaging-20220928
        version_label: ${{ github.sha }}
        deployment_package: ${{ github.sha}}-deploy.zip
        wait_for_environment_recovery: 150
        use_existing_version_if_available: true
        region: eu-west-2
      if: github.ref == 'refs/heads/blue_39'
    - name: Deploy to Staging Upgrade
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "Moodle Staging"
        environment_name: MoodleStagingUpgrade
        version_label: ${{ github.sha }}_upgrade
        deployment_package: ${{ github.sha}}-deploy.zip
        wait_for_environment_recovery: 150
        use_existing_version_if_available: true
        region: eu-west-2
      if: github.ref == 'refs/heads/blue_39_upgrade'
    - name: Deploy to UAT
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        application_name: Moodle
        environment_name: MoodleUAT
        version_label: ${{ github.sha }}_uat
        deployment_package: ${{ github.sha}}-deploy.zip
        wait_for_environment_recovery: 150
        use_existing_version_if_available: true
        region: eu-west-2
      if: github.ref == 'refs/heads/blue_39_uat'
    - name: Deploy to Production
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        application_name: Moodle
        environment_name: MoodleProd
        version_label: ${{ github.sha }}_prod
        deployment_package: ${{ github.sha}}-deploy.zip
        wait_for_environment_recovery: 150
        use_existing_version_if_available: true
        region: eu-west-2
      if: github.ref == 'refs/heads/blue_39_prod'
